name: flutter_sixvalley_ecommerce
description: A new Flutter setup application for starting a project.

publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it:
  provider:
  pdf:
  drop_down_list:
  printing:
  connectivity:
  scroll_loop_auto_scroll:
  dio:
  textfield_search:
  http:
  freezed:
  change_app_package_name:

  shared_preferences: ^2.0.5
  fancy_bottom_navigation:
  carousel_slider:
  flutter_staggered_grid_view:
  shimmer:
  url_launcher:
  image_picker:
  pull_to_refresh:

  webview_flutter:
  flutter_html: ^3.0.0-alpha.2
  share:
  photo_view:
  package_info:
  firebase_core: ^1.19.1
  firebase_storage: ^10.3.1
  firebase_auth: ^3.4.1
  firebase_messaging: ^11.4.4
  flutter_local_notifications:
  path_provider:
  google_sign_in:
  flutter_facebook_auth:
  flutter_svg:
  phone_number:
  country_code_picker:
  pin_code_fields:
  google_maps_flutter:
  flutter_google_places:
  geocoding:
  geolocator:
  flutter_typeahead:
  marquee:
  flutter_rating_bar:




dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/language/

  fonts:
    - family: HacenTunisia
      fonts:
        - asset: assets/fonts/HacenTunisia.ttf
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/ubuntu/Ubuntu-Regular.ttf
          weight: 400
        - asset: assets/fonts/ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/ubuntu/Ubuntu-Bold.ttf
          weight: 600
